name: dartstruct
description: dartstruct is an annotation processor generator using source_gen and inspired by Java MapStruct.
version: 0.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
