name: integration_tests
description:
version: 0.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dartstruct:
    path: ../core

dev_dependencies:
  build_runner:
  dartstruct_generator:
    path: ../generator
  pedantic: ^1.8.0
  test: ^1.6.0
